# Generated by Django 3.0.2 on 2020-02-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200204_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.ImageField(blank=True, default='Profiles/default-user-img.jpg', null=True, upload_to='Profiles/'),
        ),
    ]
