# Generated by Django 3.0.2 on 2020-05-23 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=120)),
                ('transaction_id', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120)),
                ('bank_txn_id', models.CharField(max_length=120)),
                ('txn_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('currency', models.CharField(max_length=50)),
                ('txn_date', models.DateTimeField()),
                ('gateway_name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('payment_mode', models.CharField(max_length=120)),
                ('payment_status', models.CharField(max_length=120)),
                ('checksumhash', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payment_Details',
            },
        ),
    ]
