# Generated by Django 3.0.2 on 2020-05-27 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20200525_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='respcode',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='pay',
            name='respmsg',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='pay',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL),
        ),
    ]
