# Generated by Django 3.0.2 on 2020-05-29 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200527_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='bank_name',
            field=models.CharField(max_length=50, verbose_name='BANK NAME'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='bank_txn_id',
            field=models.CharField(max_length=100, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='currency',
            field=models.CharField(max_length=4, verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='gateway_name',
            field=models.CharField(max_length=30, verbose_name='GATEWAY NAME'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='merchant_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pay',
            name='order_id',
            field=models.CharField(max_length=30, verbose_name='ORDER ID'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payment_mode',
            field=models.CharField(max_length=10, verbose_name='PAYMENT MODE'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payment_status',
            field=models.CharField(max_length=12, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='respcode',
            field=models.IntegerField(verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='respmsg',
            field=models.TextField(max_length=250, verbose_name='RESP MSG'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='transaction_id',
            field=models.CharField(max_length=100, verbose_name='TXN ID'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='txn_amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='txn_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE'),
        ),
    ]
