# Generated by Django 3.0.2 on 2020-05-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200529_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='bank_name',
            new_name='BANKNAME',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='bank_txn_id',
            new_name='BANKTXNID',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='currency',
            new_name='CURRENCY',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='gateway_name',
            new_name='GATEWAYNAME',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='merchant_id',
            new_name='MID',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='order_id',
            new_name='ORDERID',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='payment_mode',
            new_name='PAYMENTMODE',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='respcode',
            new_name='RESPCODE',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='respmsg',
            new_name='RESPMSG',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='payment_status',
            new_name='STATUS',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='txn_amount',
            new_name='TXNAMOUNT',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='txn_date',
            new_name='TXNDATE',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='transaction_id',
            new_name='TXNID',
        ),
    ]
