# Generated by Django 3.0.2 on 2020-05-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200529_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='checksumhash',
            new_name='CHECKSUMHASH',
        ),
    ]
