# Generated by Django 2.2.4 on 2019-11-15 07:53

from django.db import migrations, models
import sell.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('image1', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image1')),
                ('image2', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image2')),
                ('image3', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image3')),
                ('image4', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image4')),
                ('image5', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image5')),
            ],
            options={
                'db_table': 'sellpost',
            },
        ),
    ]
