# Generated by Django 2.2.4 on 2020-01-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20191115_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFurnitures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image1')),
                ('image2', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image2')),
                ('image3', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image3')),
                ('image4', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image4')),
                ('image5', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Image5')),
            ],
            options={
                'db_table': 'NewFurnitures',
            },
        ),
    ]
