# Generated by Django 3.0.2 on 2020-04-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_newfurnitures'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfurnitures',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
