# Generated by Django 3.0.2 on 2020-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_newfurnitures_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
